runner:
  clippy:
    cmd: 'find . -type f -name \*.rs -exec touch {} \;; cargo clippy --message-format json 2>&1 | clippy-reviewdog-filter'
    format: checkstyle
  rustfmt:
    cmd: 'find . -type f -name \*.rs -exec touch {} \;; cargo fmt -- --emit checkstyle 2>&1'
    format: checkstyle
